name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: |
          npm run build
          mkdir dist
          npm run package
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: xresloader/upload-to-github-release@v1
        with:
          file: "*.vsix"
          tags: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  vscode:
    name: Release to Visual Studio Marketplace
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g @vscode/vsce
      - run: vsce publish -p "${{ secrets.VS_MARKETPLACE_TOKEN }}"
